# -*- coding: utf-8 -*-
"""Assignment 1 MSDS 453.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v69I54D1G24-25hYIA_VXPsF4L09iced
"""

pip install jsonlines

import requests
from bs4 import BeautifulSoup
import pandas as pd
import jsonlines
import json

baseurl='https://www.cdc.gov/'

headers = {
    'User-Agent': 'https://developers.whatismybrowser.com/useragents/parse/720201safari-mac-os-x-webkit'
}

r = requests.get('https://www.cdc.gov/mmwr/Novel_Coronavirus_Reports.html')

soup = BeautifulSoup(r.content,'lxml')
report=soup.find_all('div',class_='col-md-12 splash-col')

links=[]
for item in report:
  for link in item.find_all('a', href=True):
    links.append(baseurl + link['href'])

print(len(links))

links[:5]

list2=links[4:]

list2



counter=0

finalList=[]
#testlink='https://www.cdc.gov/mmwr/volumes/70/wr/mm7016e1.htm?s_cid=mm7016e1_w'
for link in list2:
  r = requests.get(link,headers=headers)
  soup = BeautifulSoup(r.content,'lxml')
  counter=counter
  link=r.url
  name=soup.find('h1').text

  text=([i.text for i in soup.find_all('div', class_='order-4 w-100')])
  text=''.join(str(v) for v in text)
  docs={
      'count':counter,
      'url':link,
      'name':name,
      'text':text
  }
  counter=counter+1
  finalList.append(docs)

df=pd.DataFrame(finalList)
df.head()

dictionary = df.to_dict('reports')
with jsonlines.open('reports.jl','w') as writer:
    writer.write_all(dictionary)





